@echo off
#touch AbilityScoresTableSeeder.php
#touch AcOkTestTableSeeder.php
#touch AddressTableSeeder.php
#touch AllergenSeverityTableSeeder.php
#touch AllergenTableSeeder.php
#touch AllergiesTableSeeder.php
#touch AssignedHoursTableSeeder.php
#touch AssignedStaffTableSeeder.php
#touch ChildrenTableSeeder.php
#touch ClientAddressTableSeeder.php
#touch ClientAvailabilityTableSeeder.php
#touch ClientNameTableSeeder.php
#touch ClientPhonesTableSeeder.php
#touch ClientScheduleTableSeeder.php
#touch ClientTableSeeder.php
#touch ContactTableSeeder.php
#touch CustodyTableSeeder.php
#touch DiagnosisTableSeeder.php
#touch DrivetimeTableSeeder.php
#touch EmergencyContactsTableSeeder.php
#touch EquipmentTableSeeder.php
#touch FamilyHistoryTableSeeder.php
#touch FormsBlankTableSeeder.php
#touch FormsCompleteTableSeeder.php
#touch FormsNeededTableSeeder.php
#touch GenderTableSeeder.php
#touch GuardianTableSeeder.php
#touch HealthcareProvidersTableSeeder.php
#touch HireTableSeeder.php
#touch HomeAddressTableSeeder.php
#touch HousingConcernsTableSeeder.php
#touch IncomeTableSeeder.php
#touch InitialsTableSeeder.php
#touch InsuranceTableSeeder.php
#touch InsurerTableSeeder.php
#touch InterviewTableSeeder.php
#touch ItemTableSeeder.php
#touch LivingArrangementsTableSeeder.php
#touch LocusTestsTableSeeder.php
#touch MailAddressTableSeeder.php
#touch MaritalTableSeeder.php
#touch MedicalConcernsTableSeeder.php
#touch MedicalManagementTableSeeder.php
#touch MedicalSupportsTableSeeder.php
#touch MileageTableSeeder.php
#touch NotesTableSeeder.php
#touch OrganizationAddressTableSeeder.php
#touch OrganizationPhonesTableSeeder.php
#touch OrganizationTableSeeder.php
#touch OriginTableSeeder.php
#touch PaperworkTableSeeder.php
#touch PossibleAssisstanceSourcesTableSeeder.php
#touch PresentingProblemTableSeeder.php
 touch ProgramTableSeeder.php
#touch ProviderTypeTableSeeder.php
#touch ReferralTableSeeder.php
#touch ReferrerTableSeeder.php
#touch ReleasesTableSeeder.php
#touch RolesTableSeeder.php
#touch ShiftTableSeeder.php
#touch ShortTermDlsGoalsTableSeeder.php
#touch SsnTableSeeder.php
#touch StaffAvailabilityTableSeeder.php
#touch StaffContactInfoTableSeeder.php
#touch StaffNameTableSeeder.php
#touch StaffNotesTableSeeder.php
#touch StaffRolesTableSeeder.php
#touch StaffTableSeeder.php
#touch StaffTrainingsTableSeeder.php
#touch StateFederalEntitlementsTableSeeder.php
#touch TcmClientTableSeeder.php
#touch TimeInTableSeeder.php
#touch TimeOutTableSeeder.php
#touch TrainingScheduleTableSeeder.php
#touch TrainingsTableSeeder.php
#touch UserTableSeeder.php
#touch VehicleTableSeeder.php
#touch VocationalFinancialNeedsTableSeeder.php
#touch VocationalTableSeeder.php
#touch ZipcodesTableSeeder.php

echo "Generated Seeder Files : 79 files generated"